[package]
name = "presage-cli"
version = "0.6.0-dev"
edition = "2021"
authors = ["Gabriel FÃ©ron <g@leirbag.net>"]

[dependencies]
presage = { path = "../presage" }
presage-store-sled = { path = "../presage-store-sled" }

anyhow = "1.0"
axum = "0.6"
base64 = "0.12"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }
clap = { version = ">=4.2.4", features = ["derive"] }
directories = "3.0"
env_logger = "0.7"
futures = "0.3"
hex = "0.4"
log = "0.4"
mime_guess = "2.0"
tempfile = "3.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "io-std", "io-util"] }
qr2term = { version = "0.2.2" }
notify-rust = "4.6.0"
url = "2.2"

[features]
quirks = []
